package com.itheima.dao.system;

import com.itheima.domain.system.WechatUser;
import com.itheima.domain.system.WechatUserExample;

import java.util.List;

public interface WechatUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int insert(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int insertSelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    List<WechatUser> selectByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    WechatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WechatUser record);
}