package com.itheima.dao.feedback;

import com.itheima.domain.feedback.PeFeedback;
import com.itheima.domain.feedback.PeFeedbackExample;

import java.util.List;

public interface PeFeedbackDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int insert(PeFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int insertSelective(PeFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    List<PeFeedback> selectByExample(PeFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    PeFeedback selectByPrimaryKey(String feedbackId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PeFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pe_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PeFeedback record);
}