package com.itheima.dao.cargo;

import com.itheima.domain.cargo.PackingList;
import com.itheima.domain.cargo.PackingListExample;

import java.util.List;

public interface PackingListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String packingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    int insert(PackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    int insertSelective(PackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    List<PackingList> selectByExample(PackingListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    PackingList selectByPrimaryKey(String packingListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PackingList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table packing_list_c
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PackingList record);
}