package com.itheima.domain.system;

import java.io.Serializable;
import java.util.Date;

public class WechatUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.regdate
     *
     * @mbg.generated
     */
    private Date regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.updatedate
     *
     * @mbg.generated
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.lastdate
     *
     * @mbg.generated
     */
    private Date lastdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.online
     *
     * @mbg.generated
     */
    private Integer online;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.fanscount
     *
     * @mbg.generated
     */
    private Integer fanscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.pe_user_id
     *
     * @mbg.generated
     */
    private String peUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.id
     *
     * @return the value of wechat_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.id
     *
     * @param id the value for wechat_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.regdate
     *
     * @return the value of wechat_user.regdate
     *
     * @mbg.generated
     */
    public Date getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.regdate
     *
     * @param regdate the value for wechat_user.regdate
     *
     * @mbg.generated
     */
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.updatedate
     *
     * @return the value of wechat_user.updatedate
     *
     * @mbg.generated
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.updatedate
     *
     * @param updatedate the value for wechat_user.updatedate
     *
     * @mbg.generated
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.lastdate
     *
     * @return the value of wechat_user.lastdate
     *
     * @mbg.generated
     */
    public Date getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.lastdate
     *
     * @param lastdate the value for wechat_user.lastdate
     *
     * @mbg.generated
     */
    public void setLastdate(Date lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.online
     *
     * @return the value of wechat_user.online
     *
     * @mbg.generated
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.online
     *
     * @param online the value for wechat_user.online
     *
     * @mbg.generated
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.fanscount
     *
     * @return the value of wechat_user.fanscount
     *
     * @mbg.generated
     */
    public Integer getFanscount() {
        return fanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.fanscount
     *
     * @param fanscount the value for wechat_user.fanscount
     *
     * @mbg.generated
     */
    public void setFanscount(Integer fanscount) {
        this.fanscount = fanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.openid
     *
     * @return the value of wechat_user.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.openid
     *
     * @param openid the value for wechat_user.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.nickname
     *
     * @return the value of wechat_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.nickname
     *
     * @param nickname the value for wechat_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.avatar
     *
     * @return the value of wechat_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.avatar
     *
     * @param avatar the value for wechat_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.pe_user_id
     *
     * @return the value of wechat_user.pe_user_id
     *
     * @mbg.generated
     */
    public String getPeUserId() {
        return peUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.pe_user_id
     *
     * @param peUserId the value for wechat_user.pe_user_id
     *
     * @mbg.generated
     */
    public void setPeUserId(String peUserId) {
        this.peUserId = peUserId == null ? null : peUserId.trim();
    }
}